
Server:
 #Player-type Sentry deaths will be announced in chat.
 DieLikePlayers: false
 ExpValue: 5
 BodyguardsObeyProtection: true
 IgnoreListInvincibility: true
 
#Default stats
DefaultStats:
 Strength: 8
 Armor: 0
 Speed: 1.5
 Health: 100
 AttackRate: 1.5
 HealRate: 0.0
 NightVision: 16
 Range: 40
 WarningRange: 10
 Respawn: -1
 FollowDistance: 10
 
#Default options
DefaultOptions:
 Drops: false
 KillDrops: true
 Invincible: false
 Retaliate: true
 FriendlyFire: false
 Targetable: true
 LoadHealthLoss: 10

#Default healing items
DefaultHealing:
 CookedBeef: 8
 CookedPork: 8
 CookedMutton: 6
 CookedChicken: 6
 Bread: 5
 CookedFish: 6
 MushroomStew: 6
 Apple: 4
 MelonSlice: 2
 PumpkinPie: 8
 
#You can use <NPC> and <PLAYER> as placeholders.
DefaultTexts:
 Warning: "&c<NPC> says Halt! Come no closer!"
 Greeting: "&a<NPC> says Welcome, <PLAYER>"
 
#Default target list
DefaultTargets:
 #- "entity:monster"

 
#Default ignore list
DefaultIgnores:
 #- "entity:owner"


#Configurable messages  You can use <NPC>, <PLAYER>, <ITEM>, and <AMOUNT> as placeholders
GlobalTexts:
 Miss: "&7*** You MISS <NPC>."
 Hit: "&f*** You hit <NPC> for <AMOUNT> damage."
 Block: "&7*** You fail to penetrate <NPC>'s armor."
 Glance: "&7*** Your blow glances off <NPC> for <AMOUNT> damage."
 
AttackTypes:
 Archer: BOW

#The following items will ADD to base armor. 
#Decimals are allowed but all minecraft damge is in integers. 
#You would need 2 items of 0.3 Armor buff to add 1 point of armor.
ArmorBuffs:
 #LEATHER STUFF
 - LEATHER_HELMET 0.7
 - LEATHER_LEGGINGS 0.7
 - LEATHER_BOOTS 0.7
 - LEATHER_CHESTPLATE 4.0
 #IRON STUFF
 - IRON_HELMET 0.8
 - IRON_LEGGINGS 0.8
 - IRON_BOOTS 0.8
 - IRON_CHESTPLATE 6.0
 #DIAMOND STUFF
 - DIAMOND_HELMET 1.0
 - DIAMOND_LEGGINGS 1.0
 - DIAMOND_BOOTS 1.0
 - DIAMOND_CHESTPLATE 7.0
 
#The following items will ADD to base strength. 
StrengthBuffs:
 - IRON_SWORD 8
 - DIAMOND_SWORD 12
 - BOW 10

SpeedBuffs:


WeaponEffects:
 - BOW slow:20
 
#The following items will be equipped as helmets, can use name or id #
Helmets:
   - PUMPKIN
   - JACK_O_LANTERN
   - LEATHER_HELMET
   - CHAINMAIL_HELMET
   - GOLD_HELMET
   - IRON_HELMET
   - DIAMOND_HELMET
   
#The following items will be equipped as chestplates, can use name or id #.
Chestplates:
    - LEATHER_CHESTPLATE
    - CHAINMAIL_CHESTPLATE
    - GOLD_CHESTPLATE
    - IRON_CHESTPLATE
    - DIAMOND_CHESTPLATE
  
#The following items will be equipped as leggings, can use name or id #
Leggings:
    - LEATHER_LEGGINGS
    - CHAINMAIL_LEGGINGS
    - GOLD_LEGGINGS
    - IRON_LEGGINGS
    - DIAMOND_LEGGINGS
    
#The following items will be equipped as boots, can use name or id #
Boots:  
    - LEATHER_BOOTS
    - CHAINMAIL_BOOTS
    - GOLD_BOOTS
    - IRON_BOOTS
    - DIAMOND_BOOTS
    